### ISSUE TITLE
MCP23018 compatibility

### ISSUE THREAD

**Issue by uppfinnarjohnny** [adafruit/Adafruit-MCP23017-Arduino-Library#12]
I've tried out the library with the MCP23018 , and it (not surprisingly) seems to work just fine. I don't know if it's necessary to include in the readme, but now it at least is written somewhere. :-)

**Comment by johntalton** [comment]
the *18 device has slightly different iocon registers and will not behave as expected (specifically when using interrupts)

**Comment by caternuson** [comment]
Yep. So it probably *mostly* works. But could run into issues when hitting those differences.

![image](https://user-images.githubusercontent.com/8755041/119905011-37ae3100-bf00-11eb-8b4c-354e30e7a822.png)


![image](https://user-images.githubusercontent.com/8755041/119904971-22d19d80-bf00-11eb-9f41-f977ef89b99e.png)
