### ISSUE TITLE
digitalwrite missing endTransmission

### ISSUE THREAD

**Issue by admindotnu** [adafruit/Adafruit-MCP23017-Arduino-Library#17]
Hi,

I guess at the end of "void Adafruit_MCP23017::digitalWrite(uint8_t pin, uint8_t d) {"

Wire.endTransmission(); needs te be added. It solved completely my i2c lockup's on the due.

Thank you

**Comment by caternuson** [comment]
Closing in favor of #63 . Converting to BusIO usage will fix this as well.
