### ISSUE TITLE
Expander stops working after a while

### ISSUE THREAD

**Issue by sstaub** [adafruit/Adafruit-MCP23017-Arduino-Library#19]
- Arduino board:  UNO / Nano / Teensy 3.5
- Arduino IDE version: 1.8.5

I'm using following sketch with 2 LEDs on 6 and 7:

```
#include <Wire.h>
#include "Adafruit_MCP23017.h"

Adafruit_MCP23017 mcp;
  
void setup() {  
  mcp.begin();      // use default address 0
  mcp.pinMode(6, OUTPUT);
  mcp.pinMode(7, OUTPUT);
}

void loop() {
  delay(500);
  mcp.digitalWrite(6, HIGH);
  mcp.digitalWrite(7, LOW);
  delay(500);
  mcp.digitalWrite(6, LOW);
  mcp.digitalWrite(7, HIGH); 
}
```

After a short while (2s up to 2min) the LEDs stops blinking. I tried it on different boards, also Teensy 3.5 but can't figure out what the problem is.

**Comment by ladyada** [comment]
hiya its likely a wiring issue. please post up in the support forums of wherever you bought your hardware for assistance :)

**Comment by sstaub** [comment]
Thank you, I forgot the reset pin :)
