### ISSUE TITLE
i2c pins

### ISSUE THREAD

**Issue by ramarro123** [adafruit/Adafruit-MCP23017-Arduino-Library#21]
Hi,

i suggest to add a constructors parameter for pins for i2c.

it's useful on device like esp8266 where sometimes people need to map pin on different task

void begin(uint8_t addr);
should be
void begin(uint8_t addr, uint8_t sda = 0, uint8_t sclk = 0);

and on begin function 
if (sda != sckl)
Wire.begin(sda, sckl);
else
Wire.begin();

of course just a random implementation, but that keep compatibility with the rest of library

**Comment by ladyada** [comment]
if you want to send in a PR, we'd accept one where you pass in a Wire & object to begin(), but not individual pins! thanks :)

**Comment by stefboerrigter** [comment]
See https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/pull/38.

**Comment by caternuson** [comment]
Closing in favor of #63 . Using BusIO moves the pin assignment issue outside of this library. Instead, an I2C bus will be passed in and use whatever pins it was set up for.
