### ISSUE TITLE
private methods should be protected.

### ISSUE THREAD

**Issue by mvackel** [adafruit/Adafruit-MCP23017-Arduino-Library#25]
Hello,
it seems that all the methods declared "_private_" in the Adafruit_MCP23017 should be declared "_protected_" instead. This way we can easily write derived classes that uses those methods. There are more object oriented ways to secure the base class, but changing the declaration is sufficient for this simple class. Thanks!!

**Comment by ladyada** [comment]
hiya please submit a PR and we'll check it out :)

**Comment by caternuson** [comment]
This should be taken care of with the 2.0.0 release:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/releases/tag/2.0.0
