### ISSUE TITLE
no communication with Arduino MEGA

### ISSUE THREAD

**Issue by forsakenrecordingstudios** [adafruit/Adafruit-MCP23017-Arduino-Library#45]
i can not get any communication with the Mega board. is this because of the mega having dedicated communication pins?

**Comment by Steinies** [comment]
Probably, because currently the pins are hard coded to 4 and 5 (see issue #21).

**Comment by RoboRoyal** [comment]
By creating and then passing in a wire object I was able to communicate with a Mega 2560.
Wire.begin();
mcp.begin(address, &Wire);

**Comment by caternuson** [comment]
Closing. Looks nominally resolved. And #63 will also help with this.
