### ISSUE TITLE
Can I use mcp23017-e/ml with this library?

### ISSUE THREAD

**Issue by Dxpumpkin** [adafruit/Adafruit-MCP23017-Arduino-Library#50]
I want to use [mcp23017-e/ml](https://www.mouser.jp/ProductDetail/Microchip-Technology/MCP23017-E-ML?qs=usxtMOJb1RwOdfCNDE63wQ==) with this library

But this library is for [mcp23017](https://www.mouser.jp/ProductDetail/Microchip-Technology/MCP23017-E-SS?qs=usxtMOJb1Ry4iqG%2FOK9gBg%3D%3D) .

According to datasheet, the pin numbers are different between mcp23017-e/ml and mcp23017.

So, I'm worry about that if this library can control mcp23017-e/ml.

Can I use mcp23017-e/ml with this library?

I'm poor at English and my sentence is hard to read.Sorry.

**Comment by ladyada** [comment]
probably!
