### ISSUE TITLE
Old Version of Lib in PlatformIO

### ISSUE THREAD

**Issue by DanielSart** [adafruit/Adafruit-MCP23017-Arduino-Library#72]
Hey,

this lib is still on version 1.3 in PlatformIO.

Cheers,
Daniel

**Comment by caternuson** [comment]
I think this is something Platform IO has to do? Not sure how repo's are tied in or registered with Platform IO?

**Comment by DanielSart** [comment]
Ok thanks, I will open a post in their forums and close it if I get an answer there.

Cheers

**Comment by caternuson** [comment]
Thanks. Once it's up, please add a link to the post here. Could help others trying to figure this out, including me :) Sry, don't use PlatformIO, so not familiar with how it handles its library updating.

**Comment by caternuson** [comment]
Closing due to lack of response. Can reopen if more info provided on what is needed here.
