### ISSUE TITLE
Missing migration guide/instructions to the major 2.x release

### ISSUE THREAD

**Issue by CptHolzschnauz** [adafruit/Adafruit-MCP23017-Arduino-Library#75]
I am using the 1.3.0 version of the lib. With the new 2.x major release you changed the names of the src files, the function calls etc. without even mention it. Result: i have to recode just by compiler warnings or dive deep in the lib. 
A little readme update would be very nice on such major changes. THX

**Comment by caternuson** [comment]
The release was labeled breaking and referred to updated examples:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/releases/tag/2.0.0

**Comment by CptHolzschnauz** [comment]
Allright. I missed 2.0 and migrated to 2.2....maybe just a little hint in the readme..? Thx anyway for your work! ;=)
