### ISSUE TITLE
Provide access to INTCAP

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit-MCP23017-Arduino-Library#86]
There's already an existing (but stalled) PR that address this issue here:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/pull/84
See that thread for more background information and discussion.

Opening this so there is a dedicated issue for tracking,

**Comment by mastersta** [comment]
I'd like to throw in a vote to get this merged. Getting the INTCAP allows for using the MCP23XXX to read encoders.

**Comment by ladyada** [comment]
@caternuson is that PR fine to merge?

**Comment by caternuson** [comment]
@ladyada No. Not passing CI and no changes as yet based on feedback comments.

**Comment by caternuson** [comment]
@mastersta Can you test the suggested code changes in PR #89?

**Comment by mastersta** [comment]
@caternuson #89 tested and confirmed working as intended.

**Comment by caternuson** [comment]
@mastersta excellent. thanks for testing!

**Comment by caternuson** [comment]
Closing. Should be fixed with #89.
